# General logging configuration
logging:
  # Can be semicolon (;) separated
  # console - use a console debugger
  # rolling - use a rolling file debugger (useful for tail)
  type: console
  level: DEBUG
  file_name:
  file_path:
  message_format: '%(asctime)s - %(process)s - %(thread)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)s - %(message)s'
  file_count: 3
  max_file_bytes: 1048576

app:
  # Time for overlord to sleep between looking for open albion online ports
  port_scan_interval: 5

  # Type of scrape mode to use when gathering market information.
  # Options:
  #    * packet_capture - Listen to the traffic as network packets are transmitted
  #                       In order for packet capturing mode to work on windows please
  #                       install https://nmap.org/npcap/. Make sure to check the box to
  #                       install Npcap in WinPcap API-compatible mode. Optionally, you
  #                       will want to make sure to un-check the option to Restrict npcap
  #                       driver's access to Administrators only.
  scrape_mode: packet_capture

  # Device friendly name to scrape packets for. Required if "scrape_mode" is "packet_capture".
  # If a device on your system is found with a name in the below list then packets will be
  # captured on that device. Optionally a list value of "all" can be supplied to listen on
  # all available devices.
  scrape_devices:
      - All
#      - Example 1
#      - Example 2
#      - Intel(R) 82574L Gigabit Network Connection
#      - Intel(R) 82579V Gigabit Network Connection

  # When scrape_mode is "packet_capture", type of packet handler to use for open albion online ports. This is case sensitive.
  # Options:
  #    * NoOp:    No operation is taken
  #    * Print:   The packet bytes are printed to standard out
  packet_handler: Print
